<?php declare(strict_types=1);

/**
 * @OA\Schema(
 *     schema="Meta",
 *     required={
 *         "current_page", "first_page_url", "from", "last_page", "last_page_url", "next_page_url", "path",
 *         "per_page", "prev_page_url", "to", "total"
 *     },
 *     @OA\Property(
 *         property="first_page_url",
 *         type="string",
 *         example="http://localhost/api/activity-log/company?page=1"
 *     ),
 *     @OA\Property(property="from", type="integer", example=1),
 *     @OA\Property(property="last_page", type="integer", example=512),
 *     @OA\Property(
 *          property="last_page_url",
 *          type="string",
 *          example="http://localhost/api/activity-log/company?page=512"
 *     ),
 *     @OA\Property(
 *          property="next_page_url",
 *          type="string",
 *          example="http://localhost/api/activity-log/company?page=2"
 *     ),
 *     @OA\Property(
 *         property="path",
 *         type="string",
 *         example="http://localhost/api/activity-log/company"
 *     ),
 *     @OA\Property(property="per_page", type="integer", example=50),
 *     @OA\Property(property="prev_page_url", example="null"),
 *     @OA\Property(property="to", type="integer", example=50),
 *     @OA\Property(property="total", type="integer", example=25566)
 * )
 *
 *
 * @OA\Schema(
 *     schema="ReportSearchParams",
 *     @OA\Property(property="typeFile", type="string", description="Type file"),
 *     @OA\Property(property="listField", type="array",
 *         @OA\Items(type="string")
 *     ),
 *     @OA\Property(property="sort", type="object",
 *         @OA\Property(property="fieldName", type="company_size"),
 *         @OA\Property(property="typeSort", type="ASC"),
 *     ),
 *     @OA\Property(property="search", type="object",
 *         @OA\Property(property="responsible_id"),
 *         @OA\Property(property="created", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="updated", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="date_of_use", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="is_in_work", type="array",
 *             @OA\Items(type="boolean")
 *         ),
 *         @OA\Property(property="first_name", type="string"),
 *         @OA\Property(property="last_name", type="string"),
 *         @OA\Property(property="full_name", type="string"),
 *         @OA\Property(property="gender", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="birthday", type="object",
 *             @OA\Property(property="min", type="date", format="m-d"),
 *             @OA\Property(property="max", type="date", format="m-d"),
 *         ),
 *         @OA\Property(property="country", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="city", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="region", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="location", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="position", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="linkedin", type="string"),
 *         @OA\Property(property="social_networks", type="string"),
 *         @OA\Property(property="phones", type="string"),
 *         @OA\Property(property="skype", type="string"),
 *         @OA\Property(property="emails", type="string"),
 *         @OA\Property(property="origin", type="array",
 *             @OA\Items( type="string")
 *         ),
 *         @OA\Property(property="requires_validation", type="array",
 *             @OA\Items(type="boolean")
 *         ),
 *         @OA\Property(property="colleagues", type="string"),
 *         @OA\Property(property="colleagues_link", type="string"),
 *         @OA\Property(property="mailing_tool", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="service_id", type="string"),
 *         @OA\Property(property="added_to_mailing", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="confidence", type="object",
 *             @OA\Property(property="min", type="integer"),
 *             @OA\Property(property="max", type="integer"),
 *         ),
 *         @OA\Property(property="last_touch", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="sequence", type="string"),
 *         @OA\Property(property="status", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="opens", type="object",
 *             @OA\Property(property="min", type="integer"),
 *             @OA\Property(property="max", type="integer"),
 *         ),
 *         @OA\Property(property="views", type="object",
 *             @OA\Property(property="min", type="integer"),
 *             @OA\Property(property="max", type="integer"),
 *         ),
 *         @OA\Property(property="deliveries", type="object",
 *             @OA\Property(property="min", type="integer"),
 *             @OA\Property(property="max", type="integer"),
 *         ),
 *         @OA\Property(property="replies", type="object",
 *             @OA\Property(property="min", type="integer"),
 *             @OA\Property(property="max", type="integer"),
 *         ),
 *         @OA\Property(property="bounces", type="integer"),
 *         @OA\Property(property="mails", type="string"),
 *         @OA\Property(property="my_notes", type="string"),
 *         @OA\Property(property="sale_created", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="source", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="sale_link", type="string"),
 *         @OA\Property(property="sale_status", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="sale_project_c1", type="array",
 *             @OA\Items(type="boolean")
 *         ),
 *         @OA\Property(property="company", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="company_website", type="string"),
 *         @OA\Property(property="company_linkedin", type="string"),
 *         @OA\Property(property="company_cto", type="string"),
 *         @OA\Property(property="company_industries", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="company_size", type="object",
 *             @OA\Property(property="min", type="integer"),
 *             @OA\Property(property="max", type="integer"),
 *         ),
 *         @OA\Property(property="company_type", type="array",
 *             @OA\Items(type="string", enum={"Subsidiary", "Holding"})
 *         ),
 *         @OA\Property(property="company_subsidiary", type="string"),
 *         @OA\Property(property="company_holding", type="string"),
 *         @OA\Property(property="company_founded", type="object",
 *             @OA\Property(property="min", type="date", format="Y-m-d"),
 *             @OA\Property(property="max", type="date", format="Y-m-d"),
 *         ),
 *         @OA\Property(property="jobs", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="jobs_skills", type="array",
 *             @OA\Items(type="string")
 *         ),
 *          @OA\Property(property="jobs_urls", type="array",
 *             @OA\Items(type="string")
 *         ),
 *         @OA\Property(property="in_blacklist", type="array",
 *             @OA\Items(type="boolean")
 *         ),
 *         @OA\Property(property="comment", type="string")
 *     ),
 *     example={
 *         "typeFile": "csv",
 *         "limit": 200,
 *         "listField": {
 *             "responsible_id", "created", "updated", "first_name", "last_name", "full_name", "gender", "jobs_urls",
 *             "birthday", "country", "city", "region", "location", "position", "linkedin", "social_networks",
 *             "phones", "skype", "emails", "origin", "requires_validation", "confidence", "bounces", "in_blacklist",
 *             "colleagues", "colleagues_link", "mailing_tool", "id", "added_to_mailing", "company_subsidiary",
 *             "last_touch", "sequence", "status", "opens", "views", "deliveries", "replies", "company_industries",
 *             "mails", "my_notes", "sale_created", "source", "sale_link", "sale_status", "sale_project_c1", "company",
 *             "company_website", "company_linkedin", "company_cto", "company_size", "company_type",
 *         },
 *         "sort": {
 *             "fieldName": "company_size",
 *             "typeSort": "ASC"
 *         },
 *         "search": {
 *             "responsible_id": {15, 20, 60},
 *             "created": {"min": "2014-02-25","max": "2020-06-25"},
 *             "updated": {"min": "2020-02-25", "max": "2020-06-25" },
 *             "first_name": "Annemarie",
 *             "last_name": "Keizer",
 *             "full_name": "Tenders",
 *             "gender": {"f","m"},
 *             "birthday": {"min": "02-30", "max": "06-25"},
 *             "country": {"russia","spain"},
 *             "city": {"Minsk", "London"},
 *             "region": {"East of England", "East Midlands"},
 *             "location": {"Reply", "Paris"},
 *             "position": "Product Owner",
 *             "linkedin": "https://www.linkedin.com/in/andreaspantelis",
 *             "social_networks": "https://www.linkedin.com/company/22891",
 *             "phones": "8014716023",
 *             "skype": "napoleon02121804",
 *             "emails": "robert.naess@nordea.com",
 *             "origin": {"Kiev", "Paris"},
 *             "requires_validation": {true, false},
 *             "colleagues": "Christopher",
 *             "colleagues_link": "https://www.linkedin.com/in/brigitte-buntinx-b2a12313",
 *             "mailing_tool": {"Reply", "Google"},
 *             "service_id": "2588525",
 *             "added_to_mailing": {"min": "2020-02-25", "max": "2020-06-25"},
 *             "confidence": {"min": 25, "max": 50},
 *             "last_touch": {"min": "2020-02-25", "max": "2020-06-25"},
 *             "sequence": "sequence",
 *             "status": {"Active", "Finished"},
 *             "opens": {"min": 25, "max": 50},
 *             "views": {"min": 25,"max": 50},
 *             "deliveries": {"min": 25, "max": 50},
 *             "replies": {"min": 25,"max": 50},
 *             "bounces": 500,
 *             "mails": "webers@handwick.com",
 *             "my_notes": "myNotes test text",
 *             "sale_created": {"min": "2020-02-25","max": "2020-06-25"},
 *             "source": {"Testing", "Stoped"},
 *             "sale_link": "http://www.oocllogistics.com",
 *             "sale_status": {"Testing","Stoped"},
 *             "sale_project_c1":{true,false},
 *             "company": {"Rodenstock"},
 *             "company_website": "http://www.walvisnest.nl",
 *             "company_linkedin": "https://www.linkedin.com/company/28619843",
 *             "company_cto": "Angelas",
 *             "company_industries": {"Machinery", "Plastics"},
 *             "company_size": {"min": 25, "max": 500},
 *             "company_type": {"Subsidiary", "Holding"},
 *             "company_subsidiary": "Rodenstock",
 *             "company_holding": "Eurowings",
 *             "company_founded": {"min": "2016-05-30", "max": "2020-06-25"},
 *             "jobs": {"Program Testing", "Install docker"},
 *             "jobs_skills": {"Angular", "Solid"},
 *             "comment": "create new application"
 *         },
 *     }
 * )
 *
 *
 * @OA\Schema(
 *     schema="ParamsCompanyCreate",
 *     @OA\Property(property="name", type="string"),
 *     @OA\Property(property="website", type="string"),
 *     @OA\Property(property="linkedin", type="string"),
 *     @OA\Property(property="sto_full_name", type="string"),
 *     @OA\Property(property="type", type="string"),
 *     @OA\Property(property="skip_validation", type="boolean"),
 *     @OA\Property(property="founded", type="string", format="d.m.Y"),
 *     @OA\Property(property="min_employees", type="integer"),
 *     @OA\Property(property="max_employees", type="integer"),
 *     @OA\Property(property="comment", type="string"),
 *     @OA\Property(property="industries", type="array",
 *         @OA\Items(type="integer")
 *     ),
 *     @OA\Property(property="subsidiaries", type="array",
 *         @OA\Items(type="integer")
 *     ),
 *     @OA\Property(property="vacancies", type="array",
 *         @OA\Items(type="object",
 *             required={"job", "skills", "link"},
 *             @OA\Property(property="job", type="string"),
 *             @OA\Property(property="skills", type="string"),
 *             @OA\Property(property="link", type="string"),
 *         ),
 *     ),
 *     example={
 *         "name": "name",
 *         "website": "http://www.walvisnest.nl",
 *         "linkedin": "https://www.linkedin.com/company/22891",
 *         "sto_full_name": "Angelas",
 *         "type": "Subsidiary",
 *         "skip_validation": 1,
 *         "founded": "18.06.2020",
 *         "min_employees": 1,
 *         "max_employees": 50,
 *         "comment": "It's good company",
 *         "industries": {151, 156},
 *         "subsidiaries": {15666, 17822},
 *         "vacancies": {
 *             {
 *                 "job": "Install docker",
 *                 "skills": "Solid",
 *                 "link": "https://vitebsk.jobs.tut.by"
 *             }
 *         }
 *     }
 * )
 *
 *
 * @OA\Schema(
 *     schema="ParamsCompanyUpdate",
 *     @OA\Property(property="name", type="string"),
 *     @OA\Property(property="website", type="string"),
 *     @OA\Property(property="linkedin", type="string"),
 *     @OA\Property(property="sto_full_name", type="string"),
 *     @OA\Property(property="type", type="string"),
 *     @OA\Property(property="founded", type="string", format="d.m.Y"),
 *     @OA\Property(property="min_employees", type="integer"),
 *     @OA\Property(property="max_employees", type="integer"),
 *     @OA\Property(property="comment", type="string"),
 *     @OA\Property(property="industries", type="array",
 *         @OA\Items(type="integer")
 *     ),
 *     @OA\Property(property="subsidiaries", type="array",
 *         @OA\Items(type="integer")
 *     ),
 *     @OA\Property(property="vacancies", type="array",
 *         @OA\Items(type="object",
 *             required={"job", "skills", "link"},
 *             @OA\Property(property="id", type="integer"),
 *             @OA\Property(property="job", type="string"),
 *             @OA\Property(property="skills", type="string"),
 *             @OA\Property(property="link", type="string")
 *         ),
 *     ),
 *     example={
 *         "name": "name",
 *         "website": "http://www.walvisnest.nl",
 *         "linkedin": "https://www.linkedin.com/company/22891",
 *         "sto_full_name": "Angelas",
 *         "type": "Subsidiary",
 *         "founded": "18.06.2020",
 *         "min_employees": 1,
 *         "max_employees": 50,
 *         "comment": "It's good company",
 *         "industries": {151, 156},
 *         "subsidiaries": {15666, 17822},
 *         "vacancies": {
 *             {
 *                 "job": "Install docker",
 *                 "skills": "Solid",
 *                 "link": "https://jobs.tut.by"
 *             },
 *             {
 *                 "id": 1,
 *                 "job": "Install docker",
 *                 "skills": "Solid",
 *                 "link": "https://jobs.tut.by"
 *             }
 *         },
 *     }
 * )
 *
 *
 * @OA\Parameter(
 *     name="search",
 *     parameter="ParamsCompanySearch",
 *          in="query",
 *          required=false,
 *          style="deepObject",
 *          allowReserved=true,
 *     @OA\Property(property="name", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Andersen"))
 *     ),
 *     @OA\Property(property="created_at", type="object",
 *         required={"min", "max"},
 *         @OA\Property(property="min", type="string", format="Y-m-d", example="2014-02-25"),
 *         @OA\Property(property="max", type="string", format="Y-m-d", example="2014-02-25"),
 *     ),
 *     @OA\Property(property="updated_at", type="object",
 *         required={"min", "max"},
 *         @OA\Property(property="min", type="string", format="Y-m-d", example="2014-02-25"),
 *         @OA\Property(property="max", type="string", format="Y-m-d", example="2014-02-25"),
 *     ),
 *     @OA\Property(property="website", type="string", example="http://www.walvisnest.nl"),
 *     @OA\Property(property="linkedin", type="string", example="https://www.linkedin.com/company/28619843"),
 *     @OA\Property(property="sto_full_name", type="string", example="Angelas"),
 *     @OA\Property(property="founded", type="object",
 *         required={"min", "max"},
 *         @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *         @OA\Property(property="max", type="date", format="Y-m-d", example="2020-02-25"),
 *     ),
 *     @OA\Property(property="industry", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Machinery"))
 *     ),
 *     @OA\Property(property="company_size", type="object",
 *         required={"min", "max"},
 *         @OA\Property(property="min", type="integer", example=51),
 *         @OA\Property(property="max", type="integer", example=100),
 *     ),
 *     @OA\Property(property="type", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", enum={"Subsidiary", "Holding"}))
 *     ),
 *     @OA\Property(property="jobs", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Program Testing"))
 *     ),
 *     @OA\Property(property="skills", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Angular"))
 *     ),
 * )
 *
 *
 * @OA\Parameter(
 *     name="sort",
 *     in="query",
 *     required=false,
 *     parameter="ParamsCompanySort",
 *     @OA\Property(property="sort", type="object",
 *          required={"field_name", "type_sort"},
 *          @OA\Property(property="field_name", type="date", enum={"id", "created_at", "updated_at",
 *               "website", "name", "linkedin", "sto_full_name", "type", "founded", "comment"}),
 *          @OA\Property(property="type_sort", type="string", enum={"ASC", "DESC"}),
 *     ),
 * )
 *
 *
 * @OA\Schema(
 *     schema="ParamsStartImport",
 *     required={"fields", "responsible", "is_headers", "duplication_action"},
 *     @OA\Property(property="fields", type="array",
 *         @OA\Items(type="string", enum={
 *             "first_name", "last_name", "email", "company", "phone", "city", "region", "country",
 *             "c_linkedin", "comp_linkedin", "position", "website", "industry", "comp_size",
 *             "confidence", "c_comment", "comp_comment", "service_id", "added_to_mailing",
 *             "sequence", "status", "opens", "views", "deliveries", "replies", "bounces", "skip"
 *         })),
 *         @OA\Property(property="origin", type="array",
 *              @OA\Items(type="string",enum={"NC1", "NC2", "Parser", "Purchase", "Legacy", "Reply", "Lemlist"})
 *         ),
 *         @OA\Property(property="comment", type="string"),
 *         @OA\Property(property="responsible", type="number"),
 *         @OA\Property(property="column_separator", type="string", enum={"semicolon", "comma", "space", "tab"}),
 *         @OA\Property(property="is_headers", type="boolean", enum={1, 0, true, false}),
 *         @OA\Property(property="duplication_action", type="string", enum={"replace", "merge", "skip"}),
 *         example={
 *            "fields": {"first_name", "last_name", "email"},
 *            "origin": {"Reply", "Lemlist"},
 *            "comment": "Is good worker",
 *            "responsible": 3,
 *            "column_separator": "semicolon",
 *            "is_headers": 1,
 *            "duplication_action": "replace"
 *         }
 *     )
 * )
 *
 *
 * @OA\Schema(
 *     schema="ParamsContactCreate",
 *     required={"emails", "requires_validation"},
 *     @OA\Property(property="emails", type="array",
 *         @OA\Items(type="string")
 *     ),
 *     @OA\Property(property="phones", type="array",
 *         @OA\Items(type="string"),
 *     ),
 *     @OA\Property(property="first_name", type="string"),
 *     @OA\Property(property="last_name", type="string"),
 *     @OA\Property(property="full_name", type="string"),
 *     @OA\Property(property="gender", type="string", enum={"f", "m"}),
 *     @OA\Property(property="linkedin", type="string"),
 *     @OA\Property(property="requires_validation", type="boolean"),
 *     @OA\Property(property="location", type="object",
 *         @OA\Property(property="country", type="string"),
 *         @OA\Property(property="region", type="string"),
 *         @OA\Property(property="city", type="string"),
 *     ),
 *     @OA\Property(property="position", type="string"),
 *     @OA\Property(property="colleagues", type="array",
 *         @OA\Items(type="object",
 *             @OA\Property(property="link", type="string"),
 *             @OA\Property(property="full_name", type="string"),
 *         ),
 *     ),
 *     @OA\Property(property="social_networks", type="string"),
 *     @OA\Property(property="comment", type="string"),
 *     @OA\Property(property="company_id", type="integer"),
 *     @OA\Property(property="skype", type="string"),
 *     @OA\Property(property="last_touch", type="date", format="Y-m-d"),
 *     @OA\Property(property="mailing_tool", type="string"),
 *     @OA\Property(property="added_to_mailing", type="date", format="Y-m-d"),
 *     @OA\Property(property="responsible", type="string"),
 *     @OA\Property(property="origin", type="string"),
 *     @OA\Property(property="birthday", type="date", format="Y-m-d"),
 *     @OA\Property(property="opens", type="integer"),
 *     @OA\Property(property="views", type="integer"),
 *     @OA\Property(property="deliveries", type="integer"),
 *     @OA\Property(property="replies", type="integer"),
 *     @OA\Property(property="bounces", type="integer"),
 *     @OA\Property(property="confidence", type="integer"),
 *     @OA\Property(property="service_id", type="string"),
 *     example={
 *         "emails": {"test1@test.com", "test2@test.com"},
 *         "phones": {"+375338447755", "+79114477555"},
 *         "first_name": "first",
 *         "last_name": "last",
 *         "full_name": "full",
 *         "gender": "f",
 *         "linkedin": "http://test.com/122",
 *         "requires_validation": 1,
 *         "location": {
 *             "country": "Belarus",
 *             "region": "Vitebsk",
 *             "city": "Polotsk",
 *         },
 *         "social_networks": "http://vk.com/1233",
 *         "comment": "Is good worker",
 *         "company_id": 1,
 *         "skype": "skype",
 *         "last_touch": "2020-03-12",
 *         "mailing_tool": "replay",
 *         "added_to_mailing": "2020-03-12",
 *         "responsible": "Ivan",
 *         "origin": "origin",
 *         "birthday": "1995-03-12",
 *         "opens": 15,
 *         "views": 1,
 *         "deliveries": 2,
 *         "replies": 1,
 *         "bounces": 0,
 *         "confidence": 99,
 *         "service_id": "1235594456"
 *     }
 * )
 *
 *
 * @OA\Schema(
 *     schema="ParamsContactUpdate",
 *     @OA\Property(property="emails", type="array",
 *         @OA\Items(type="string"),
 *     ),
 *     @OA\Property(property="phones", type="array",
 *         @OA\Items(type="string"),
 *     ),
 *     @OA\Property(property="first_name", type="string"),
 *     @OA\Property(property="last_name", type="string"),
 *     @OA\Property(property="full_name", type="string"),
 *     @OA\Property(property="gender", type="string", enum={"f", "m"}),
 *     @OA\Property(property="linkedin", type="string"),
 *     @OA\Property(property="requires_validation", type="boolean"),
 *     @OA\Property(property="location", type="object",
 *         @OA\Property(property="country", type="string"),
 *         @OA\Property(property="region", type="string"),
 *         @OA\Property(property="city", type="string"),
 *     ),
 *     @OA\Property(property="position", type="string"),
 *     @OA\Property(property="social_networks", type="string"),
 *     @OA\Property(property="skype", type="string"),
 *     @OA\Property(property="origin", type="string"),
 *     @OA\Property(property="opens", type="integer"),
 *     @OA\Property(property="views", type="integer"),
 *     @OA\Property(property="deliveries", type="integer"),
 *     @OA\Property(property="replies", type="integer"),
 *     @OA\Property(property="bounces", type="integer"),
 *     @OA\Property(property="confidence", type="integer"),
 *     @OA\Property(property="company_id", type="integer"),
 *     @OA\Property(property="last_touch", type="date", format="Y-m-d"),
 *     @OA\Property(property="mailing_tool", type="string"),
 *     @OA\Property(property="added_to_mailing", type="date", format="Y-m-d"),
 *     @OA\Property(property="responsible", type="string"),
 *     @OA\Property(property="birthday", type="date", format="Y-m-d"),
 *     @OA\Property(property="service_id", type="string"),
 *     @OA\Property(property="comment", type="string"),
 *     @OA\Property(property="note", type="array",
 *         @OA\Items(type="string")
 *     ),
 *     example={
 *         "emails": {"test1@test.com", "test2@test.com"},
 *         "phones": {"+375338447755", "+79114477555"},
 *         "first_name": "first",
 *         "last_name": "last",
 *         "full_name": "full",
 *         "gender": "f",
 *         "linkedin": "http://test.com/122",
 *         "requires_validation": 1,
 *         "location": {
 *             "country": "Belarus",
 *             "region": "Vitebsk",
 *             "city": "Polotsk",
 *         },
 *         "social_networks": "http://vk.com/1265",
 *         "company_id": 1,
 *         "skype": "skype",
 *         "last_touch": "2020-03-12",
 *         "mailing_tool": "replay",
 *         "added_to_mailing": "2020-03-12",
 *         "responsible": "Ivan",
 *         "origin": "origin",
 *         "birthday": "1995-03-12",
 *         "opens": 15,
 *         "views": 1,
 *         "deliveries": 2,
 *         "replies": 1,
 *         "bounces": 0,
 *         "confidence": 99,
 *         "service_id": "1235594456",
 *         "note": {"test To the test"}
 *     }
 * )
 *
 *
 * @OA\Parameter(
 *     name="search",
 *     parameter="searchChangeResponsoble",
 *     in="query",
 *     required=false,
 *     style="deepObject",
 *     allowReserved=true,
 *     @OA\Property(property="responsible", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Igor"))
 *     ),
 *     @OA\Property(property="created_at", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="string", format="Y-m-d", example="2014-02-25"),
 *         @OA\Property(property="max", type="string", format="Y-m-d", example="2014-02-25"),
 *     ),
 *       @OA\Property(property="updated_at", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="string", format="Y-m-d", example="2014-02-25"),
 *           @OA\Property(property="max", type="string", format="Y-m-d", example="2014-02-25"),
 *       ),
 *       @OA\Property(property="first_name", type="string", example="Annemarie"),
 *       @OA\Property(property="last_name", type="string", example="Keizer"),
 *       @OA\Property(property="full_name", type="string", example="Annemarie Keizer"),
 *       @OA\Property(property="gender", type="array",
 *           @OA\Items(type="object", @OA\Property(type="string", enum={"m","f"}))
 *       ),
 *       @OA\Property(property="birthday", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="string", format="m-d", example="02-30"),
 *           @OA\Property(property="max", type="string", format="m-d", example="06-25"),
 *       ),
 *       @OA\Property(property="country", type="array",
 *           @OA\Items(type="object", @OA\Property(type="string", example="russia"))
 *       ),
 *       @OA\Property(property="city", type="array",
 *           @OA\Items(type="object", @OA\Property(type="string", example="London"))
 *       ),
 *       @OA\Property(property="region", type="array",
 *           @OA\Items(type="object", @OA\Property(type="string", example="East Midlands"))
 *       ),
 *       @OA\Property(property="position", type="string", example="Product Owner"),
 *       @OA\Property(property="linkedin", type="string", example="https://www.linkedin.com/in/andreaspantelis"),
 *       @OA\Property(property="social_networks", type="string", example="https://www.linkedin.com/company/22891"),
 *       @OA\Property(property="phone", type="string", example="8014716023"),
 *       @OA\Property(property="skype", type="string", example="napoleon02121804"),
 *       @OA\Property(property="email", type="string", example="robert.naess@nordea.com"),
 *       @OA\Property(property="origin", type="array",
 *           @OA\Items(type="object", @OA\Property(type="string", example="Kiev"))
 *       ),
 *       @OA\Property(property="requires_validation", type="boolean", example=1),
 *       @OA\Property(property="mailing_tool", type="array",
 *           @OA\Items(type="string", type="object", @OA\Property(type="string",example="Reply"))
 *       ),
 *       @OA\Property(property="service_id", type="integer", example="123654"),
 *       @OA\Property(property="added_to_mailing", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *           @OA\Property(property="max", type="date", format="Y-m-d", example="2020-06-25"),
 *       ),
 *       @OA\Property(property="confidence", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="integer", example=25),
 *           @OA\Property(property="max", type="integer", example=50),
 *       ),
 *       @OA\Property(property="last_touch", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *           @OA\Property(property="max", type="date", format="Y-m-d", example="2020-02-25"),
 *       ),
 *       @OA\Property(property="sequence", type="string", example="sequence"),
 *       @OA\Property(property="status", type="array",
 *           @OA\Items(type="object", @OA\Property(type="string", example="Active"))
 *       ),
 *       @OA\Property(property="opens", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="integer", example=25),
 *           @OA\Property(property="max", type="integer", example=50),
 *       ),
 *       @OA\Property(property="views", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="integer", example=25),
 *           @OA\Property(property="max", type="integer", example=50),
 *       ),
 *       @OA\Property(property="deliveries", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="integer", example=25),
 *           @OA\Property(property="max", type="integer", example=50),
 *       ),
 *       @OA\Property(property="replies", type="object", required={"min", "max"},
 *           @OA\Property(property="min", type="integer", example=25),
 *           @OA\Property(property="max", type="integer", example=50),
 *       ),
 *       @OA\Property(property="bounces", type="integer", example=25),
 *       @OA\Property(property="mails", type="string", example="webers@handwick.com"),
 *       @OA\Property(property="my_notes", type="string", example="myNotes test text"),
 *       @OA\Property(property="comment", type="string", example="create new application"),
 *       @OA\Property(property="sale", type="object",
 *           @OA\Property(property="created_at", type="object", required={"min", "max"},
 *               @OA\Property(property="min", type="string", format="Y-m-d", example="2020-02-25"),
 *               @OA\Property(property="max", type="string", format="Y-m-d", example="2020-02-25"),
 *           ),
 *           @OA\Property(property="source", type="array",
 *               @OA\Items(type="object", @OA\Property(type="string", example="Testing"))
 *           ),
 *           @OA\Property(property="link", type="string", example="http://www.oocllogistics.com"),
 *           @OA\Property(property="status", type="array",
 *               @OA\Items(type="object", @OA\Property(type="string", example="Testing"))
 *           ),
 *           @OA\Property(property="project_c1", type="boolean", example=1),
 *     ),
 *     @OA\Property(property="company", type="object",
 *         @OA\Property(property="name", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Rodenstock"))
 *         ),
 *         @OA\Property(property="website", type="string", example="http://www.walvisnest.nl"),
 *         @OA\Property(property="linkedin", type="string", example="https://www.linkedin.com/company/28619843"),
 *         @OA\Property(property="sto_full_name", type="string", example="Angelas"),
 *         @OA\Property(property="founded", type="object", required={"min", "max"},
 *             @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *             @OA\Property(property="max", type="date", format="Y-m-d", example="2020-02-25"),
 *         ),
 *         @OA\Property(property="industry", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Machinery"))
 *         ),
 *         @OA\Property(property="company_size", type="object", required={"min", "max"},
 *             @OA\Property(property="min", type="integer", example=51),
 *             @OA\Property(property="max", type="integer", example=100),
 *         ),
 *         @OA\Property(property="type", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", enum={"Subsidiary", "Holding"}))
 *         ),
 *         @OA\Property(property="jobs", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Program Testing"))
 *         ),
 *         @OA\Property(property="skills", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Angular"))
 *         ),
 *         @OA\Property(property="link", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="jobs.tut.by"))
 *         ),
 *         @OA\Property(property="subsidiary", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Casino"))
 *         ),
 *         @OA\Property(property="holding", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Somention"))
 *         ),
 *    ),
 * )
 *
 *
 * @OA\Parameter(
 *     name="sort",
 *     parameter="contactSort",
 *     in="query",
 *     required=false,
 *     @OA\Schema(
 *         type="object",
 *         required={"field_name", "type_sort"},
 *         @OA\Property(property="sort", type="object",
 *             required={"field_name", "type_sort"},
 *             @OA\Property(property="field_name", type="date", enum={"id","responsible","created_at", "updated_at",
 *                 "first_name","last_name","full_name","gender","birthday","country", "region","city","position",
 *                 "linkedin", "skype", "last_touch", "added_to_mailing", "origin", "mailing_tool", "confidence",
 *                 "opens","views","deliveries","bounces","replies","service_id","comment"}),
 *             @OA\Property(property="type_sort", type="string", enum={"ASC", "DESC"}),
 *         ),
 *     )
 * ),
 *
 * @OA\Parameter(
 *     name="search",
 *     parameter="contactSearh",
 *     in="query",
 *     required=false,
 *     style="deepObject",
 *     allowReserved=true,
 *     @OA\Property(property="responsible", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Igor"))
 *     ),
 *     @OA\Property(property="created_at", type="object",
 *         required={"min", "max"},
 *         @OA\Property(property="min", type="string", format="Y-m-d", example="2014-02-25"),
 *         @OA\Property(property="max", type="string", format="Y-m-d", example="2014-02-25"),
 *     ),
 *     @OA\Property(property="updated_at", type="object",
 *         required={"min", "max"},
 *         @OA\Property(property="min", type="string", format="Y-m-d", example="2014-02-25"),
 *         @OA\Property(property="max", type="string", format="Y-m-d", example="2014-02-25"),
 *     ),
 *     @OA\Property(property="first_name", type="string", example="Annemarie"),
 *     @OA\Property(property="last_name", type="string", example="Keizer"),
 *     @OA\Property(property="full_name", type="string", example="Annemarie Keizer"),
 *     @OA\Property(property="gender", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", enum={"m","f"}))
 *     ),
 *     @OA\Property(property="birthday", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="string", format="m-d", example="02-30"),
 *         @OA\Property(property="max", type="string", format="m-d", example="06-25"),
 *     ),
 *     @OA\Property(property="country", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="russia"))
 *     ),
 *     @OA\Property(property="city", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="London"))
 *     ),
 *     @OA\Property(property="region", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="East Midlands"))
 *     ),
 *     @OA\Property(property="position", type="string", example="Product Owner"),
 *     @OA\Property(property="linkedin",type="string", example="https://www.linkedin.com/in/andreaspantelis"),
 *     @OA\Property(property="social_networks", type="string", example="https://www.linkedin.com/company/22891"),
 *     @OA\Property(property="phone", type="string", example="8014716023"),
 *     @OA\Property(property="skype", type="string", example="napoleon02121804"),
 *     @OA\Property(property="email", type="string", example="robert.naess@nordea.com"),
 *     @OA\Property(property="origin", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Kiev"))
 *     ),
 *     @OA\Property(property="requires_validation", type="boolean", example=1),
 *     @OA\Property(property="colleague_name", type="string", example="Christopher"),
 *     @OA\Property(
 *         property="colleague_link",
 *         type="string",
 *         example="https://www.linkedin.com/in/brigitte-buntinx-b2a12313"
 *     ),
 *     @OA\Property(property="mailing_tool", type="array",
 *         @OA\Items(type="string", type="object", @OA\Property(type="string",example="Reply"))
 *     ),
 *     @OA\Property(property="service_id", type="string", example=123654),
 *     @OA\Property(property="added_to_mailing", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *         @OA\Property(property="max", type="date", format="Y-m-d", example="2020-06-25"),
 *     ),
 *     @OA\Property(property="confidence", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="integer", example=25),
 *         @OA\Property(property="max", type="integer", example=50),
 *     ),
 *     @OA\Property(property="last_touch", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *         @OA\Property(property="max", type="date", format="Y-m-d", example="2020-02-25"),
 *     ),
 *     @OA\Property(property="sequence", type="string", example="sequence"),
 *     @OA\Property(property="status", type="array",
 *         @OA\Items(type="object", @OA\Property(type="string", example="Active"))
 *     ),
 *     @OA\Property(property="opens", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="integer", example=25),
 *         @OA\Property(property="max", type="integer", example=50),
 *     ),
 *     @OA\Property(property="views", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="integer", example=25),
 *         @OA\Property(property="max", type="integer", example=50),
 *     ),
 *     @OA\Property(property="deliveries", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="integer", example=25),
 *         @OA\Property(property="max", type="integer", example=50),
 *     ),
 *     @OA\Property(property="replies", type="object", required={"min", "max"},
 *         @OA\Property(property="min", type="integer", example=25),
 *         @OA\Property(property="max", type="integer", example=50),
 *     ),
 *     @OA\Property(property="bounces", type="integer", example=25),
 *     @OA\Property(property="mails", type="string", example="webers@handwick.com"),
 *     @OA\Property(property="my_notes", type="string", example="myNotes test text"),
 *     @OA\Property(property="comment", type="string", example="create new application"),
 *     @OA\Property(property="sale", type="object",
 *         @OA\Property(property="created_at", type="object", required={"min", "max"},
 *             @OA\Property(property="min", type="string", format="Y-m-d", example="2020-02-25"),
 *             @OA\Property(property="max", type="string", format="Y-m-d", example="2020-02-25"),
 *         ),
 *         @OA\Property(property="source", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Testing"))
 *         ),
 *         @OA\Property(property="link", type="string", example="http://www.oocllogistics.com"),
 *         @OA\Property(property="status", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Testing"))
 *         ),
 *         @OA\Property(property="project_c1", type="boolean", example=1),
 *     ),
 *     @OA\Property(property="company", type="object",
 *         @OA\Property(property="name", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Rodenstock"))
 *         ),
 *         @OA\Property(property="website", type="string", example="http://www.walvisnest.nl"),
 *         @OA\Property(property="linkedin",type="string",example="https://www.linkedin.com/company/28619843"),
 *         @OA\Property(property="sto_full_name", type="string", example="Angelas"),
 *         @OA\Property(property="founded", type="object", required={"min", "max"},
 *             @OA\Property(property="min", type="date", format="Y-m-d", example="2020-02-25"),
 *             @OA\Property(property="max", type="date", format="Y-m-d", example="2020-02-25"),
 *         ),
 *         @OA\Property(property="industry", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Machinery"))
 *         ),
 *         @OA\Property(property="company_size", type="object", required={"min", "max"},
 *             @OA\Property(property="min", type="integer", example=51),
 *             @OA\Property(property="max", type="integer", example=100),
 *         ),
 *         @OA\Property(property="type", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", enum={"Subsidiary", "Holding"}))
 *         ),
 *         @OA\Property(property="jobs", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Program Testing"))
 *         ),
 *         @OA\Property(property="skills", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Angular"))
 *         ),
 *         @OA\Property(property="link", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="jobs.tut.by"))
 *         ),
 *         @OA\Property(property="subsidiary", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Casino"))
 *         ),
 *         @OA\Property(property="holding", type="array",
 *             @OA\Items(type="object", @OA\Property(type="string", example="Somention"))
 *         ),
 *     ),
 * )
 *
 *
 * @OA\Schema(
 *     schema="ParamsUserCreateAndUpdate",
 *     required={"email", "login", "name", "surname", "skype", "active", "roles"},
 *     @OA\Property(property="email", type="string", example="masscrm@andersenlab.com"),
 *     @OA\Property(property="login", type="string", example="masscrm"),
 *     @OA\Property(property="name", type="string", example="name-masscrm"),
 *     @OA\Property(property="surname", type="string", example="surname-masscrm"),
 *     @OA\Property(property="position", type="string", example="position-masscrm"),
 *     @OA\Property(property="comment", type="string", example="comment-masscrm"),
 *     @OA\Property(property="skype", type="string", example="skype:skype555"),
 *     @OA\Property(property="active", type="boolean", example=true),
 *     @OA\Property(property="roles", type="array",
 *         @OA\Items(type="string", example="administrator")
 *     ),
 * )
 *
 * @OA\Schema(
 *     schema="ImportUploadFile",
 *     @OA\Property(property="file_size", type="string", example="6.2 kb"),
 *     @OA\Property(property="data", type="object",
 *         @OA\Property(property="headers", type="array",
 *             @OA\Items(type="string", example="First Name")
 *         ),
 *         @OA\Property(property="rows", type="array",
 *             @OA\Items(type="array",
 *                 @OA\Items(type="string", example="Bendikt"),
 *             )
 *         )
 *     ),
 * )
 *
 *
 * @OA\Parameter(
 *     name="page",
 *     parameter="page",
 *     in="query",
 *     required=false,
 *     description="Current page",
 *     @OA\Schema(type="integer")
 * )
 *
 *
 * @OA\Parameter(
 *     name="limit",
 *     parameter="limit",
 *     in="query",
 *     required=false,
 *     description="Limit record",
 *     @OA\Schema(type="integer")
 * )
 *
 *
 * @OA\Parameter(
 *     name="id",
 *     parameter="id",
 *     in="path",
 *     required=true,
 *     @OA\Schema(type="integer")
 * ),
 */
