version: '3.3'

services:
  php-fpm:
    image: nexus-docker.andersenlab.dev/php-fpm7.4-masscrm:prod
    container_name: php-fpm7.4-masscrm
    restart: always
    ports:
      - 9000:9000
      - 8090:8090
    volumes:
      - /dockerlogs/server_logs_fpm:/var/log/docker
      - /dockerlogs/storage_logs_fpm:/var/www/storage/logs
      # - /dockerlogs/files_fpm:/var/www/storage/files


  nginx:
    image: nexus-docker.andersenlab.dev/nginx-masscrm:prod
    container_name: nginx-masscrm
    restart: always
    ports:
      - 80:80
    volumes:
      - /dockerlogs/server_logs_nginx:/var/log/nginx
      - /dockerlogs/storage_logs_nginx:/var/www/storage/logs
      # - /dockerlogs/files_nginx:/var/www/storage/files
    depends_on:
      - php-fpm


  redis:
    image: nexus-docker.andersenlab.dev/redis-masscrm:prod
    container_name: redis-masscrm
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    restart: always
    ports:
      - 1080:1080
      - 1025:1025

  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


volumes:
  redis:
  elasticsearch-data:
