FROM nginx:1.15

RUN usermod -u 1000 www-data

RUN rm /etc/nginx/conf.d/default.conf
ADD docker/nginx/nginx.conf /etc/nginx/nginx.conf
ADD docker/nginx/server.conf /etc/nginx/conf.d/


RUN mkdir -pv /var/www && chown -R www-data:www-data /var/www
USER www-data
COPY --chown=www-data:www-data . /var/www/
RUN ls -lah /var/www
#RUN chown -R www-data:www-data /var/www
#COPY --from=php-fpm-7.4 /src /var/www/
EXPOSE 80
EXPOSE 443
